In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [5]:
df = pd.read_csv("data/educational-facilities-in-nigeria.csv", encoding="latin1")
df.head(10)

C:\Users\user\AppData\Local\Temp\ipykernel_3480\949455507.py:1: DtypeWarning: Columns (0: improved_water_supply, 1: improved_sanitation, 2: phcn_electricity) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/educational-facilities-in-nigeria.csv", encoding="latin1")

,facility_name,facility_type_display,improved_water_supply,improved_sanitation,chalkboard_each_classroom_yn,num_tchrs_with_nce,num_tchr_full_time,num_students_total,num_classrms_total,phcn_electricity,...,community,ward,management,sector,formhub_photo_id,gps,survey_id,unique_lga,latitude,longitude
0,CPS SWALI,Primary school only,True,True,False,9.0,9.0,776.0,12.0,False,...,Swali,3,public,education,1393404015008.jpg,4.91691036 6.27412844 31.5 5.0,51885096-65a1-4f1f-8c2a-3b11d9ae40bb,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,False,False,NaN,NaN,NaN,NaN,NaN,False,...,Mpape,Dutse,private,education,1396960914896.jpg,9.140918333333333 7.496761666666667 697.0 4.5,7f3ea41a-e4cb-41dd-85fc-5fa54c42d09f,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,True,True,False,9.0,11.0,283.0,9.0,False,...,Pabeyi,Dobi,public,education,1397575395444.jpg,9.174855 7.0220616666666675 236.8 5.0,56f2e625-ec43-4c39-97a8-d6379dceefa2,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,False,True,False,4.0,5.0,247.0,7.0,False,...,Pagadna,Dobi,public,education,1398262573409.jpg,9.115846666666666 6.962314999999999 216.5 4.4,2932eda8-64b1-4068-8412-3b2e099062fc,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,False,True,True,4.0,8.0,66.0,10.0,True,...,Mpape,Dutse,private,education,1396959110576.jpg,9.141155 7.499665000000001 693.2 4.7,e17acb1e-364a-4a90-9384-0d612bb240c5,fct_bwari,9.141155,7.499665
5,Nomadic Paiko Kore,Primary school only,True,True,True,4.0,6.0,120.0,6.0,False,...,Paiko Kore,Paiko,public,education,1398330459520.jpg,8.99146 7.0096750000000005 170.9 5.0,28d8fe5a-7a18-4d17-9f64-7ae095eb1c50,fct_gwagwalada,8.991460,7.009675
6,Nomadic Jayi,Primary school only,True,True,True,4.0,4.0,152.0,9.0,False,...,Jayi,Dobi,public,education,1397572115063.jpg,9.204203333333334 7.015148333333333 271.4 4.5,31381276-73f9-4e30-acde-bec286919256,fct_gwagwalada,9.204203,7.015148
7,Nomadic Kutunku,Primary school only,True,True,False,7.0,10.0,245.0,10.0,True,...,Kutunku,Kutunku,public,education,1398345111978.jpg,8.934686666666666 7.056360000000001 174.9 4.6,76a5fbc9-6723-467a-939d-703a3702ec53,fct_gwagwalada,8.934687,7.056360
8,Bargada Primary School,Primary school only,False,True,False,4.0,5.0,181.0,10.0,False,...,Bargada,Paiko,public,education,1398340786686.jpg,8.921268333333334 6.959628333333335 161.8 4.3,6bd36fb3-704a-49ad-a96a-b25b24af78d3,fct_gwagwalada,8.921268,6.959628
9,Macbeth Intl School,Primary and Junior Secondary school combined,True,True,True,3.0,6.0,80.0,6.0,False,...,Byazhin,Byazhin,private,education,1397485980654.jpg,9.19196 7.3325966666666655 455.2 3.8,7e344ad8-c442-4138-a869-6ce98794beaa,fct_bwari,9.191960,7.332597

In [6]:
df.shape

(98667, 28)

In [10]:
# Check the columns
# df.columns
for column in df.columns:
    print(column)

facility_name
facility_type_display
improved_water_supply
improved_sanitation
chalkboard_each_classroom_yn
num_tchrs_with_nce
num_tchr_full_time
num_students_total
num_classrms_total
phcn_electricity
num_toilets_total
num_students_male
num_students_female
num_tchrs_male
num_tchrs_female
date_of_survey
education_type
facility_id
community
ward
management
sector
formhub_photo_id
gps
survey_id
unique_lga
latitude
longitude

In [11]:
df.dtypes

facility_name                       str
facility_type_display               str
improved_water_supply            object
improved_sanitation              object
chalkboard_each_classroom_yn     object
num_tchrs_with_nce              float64
num_tchr_full_time              float64
num_students_total              float64
num_classrms_total              float64
phcn_electricity                 object
num_toilets_total               float64
num_students_male               float64
num_students_female             float64
num_tchrs_male                  float64
num_tchrs_female                float64
date_of_survey                      str
education_type                      str
facility_id                         str
community                           str
ward                                str
management                          str
sector                              str
formhub_photo_id                    str
gps                                 str
survey_id                           str
unique_lga                          str
latitude                        float64
longitude                       float64
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98667 entries, 0 to 98666
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   facility_name                 98452 non-null  str
 1   facility_type_display         97764 non-null  str
 2   improved_water_supply         98388 non-null  object
 3   improved_sanitation           98370 non-null  object
 4   chalkboard_each_classroom_yn  96506 non-null  object
 5   num_tchrs_with_nce            95137 non-null  float64
 6   num_tchr_full_time            96503 non-null  float64
 7   num_students_total            93405 non-null  float64
 8   num_classrms_total            95375 non-null  float64
 9   phcn_electricity              98390 non-null  object
 10  num_toilets_total             95705 non-null  float64
 11  num_students_male             94292 non-null  float64
 12  num_students_female           94321 non-null  float64
 13  num_tchrs_male                94987 non-null  float64
 14  num_tchrs_female              95348 non-null  float64
 15  date_of_survey                98667 non-null  str
 16  education_type                98446 non-null  str
 17  facility_id                   98667 non-null  str
 18  community                     98429 non-null  str
 19  ward                          97896 non-null  str
 20  management                    97444 non-null  str
 21  sector                        98667 non-null  str
 22  formhub_photo_id              98667 non-null  str
 23  gps                           98667 non-null  str
 24  survey_id                     98667 non-null  str
 25  unique_lga                    98666 non-null  str
 26  latitude                      98667 non-null  float64
 27  longitude                     98667 non-null  float64
dtypes: float64(11), object(4), str(13)
memory usage: 41.3+ MB

In [14]:
# Check the number of missing values
missing_values = df.isnull().sum()
missing_values

facility_name                    215
facility_type_display            903
improved_water_supply            279
improved_sanitation              297
chalkboard_each_classroom_yn    2161
num_tchrs_with_nce              3530
num_tchr_full_time              2164
num_students_total              5262
num_classrms_total              3292
phcn_electricity                 277
num_toilets_total               2962
num_students_male               4375
num_students_female             4346
num_tchrs_male                  3680
num_tchrs_female                3319
date_of_survey                     0
education_type                   221
facility_id                        0
community                        238
ward                             771
management                      1223
sector                             0
formhub_photo_id                   0
gps                                0
survey_id                          0
unique_lga                         1
latitude                           0
longitude                          0
dtype: int64

In [15]:
# Investigate those suspicious columns
df["improved_water_supply"].value_counts(dropna=False)

improved_water_supply
False    60954
True     37434
NaN        279
Name: count, dtype: int64

In [16]:
df["improved_sanitation"].value_counts(dropna=False)

improved_sanitation
False    53032
True     45338
NaN        297
Name: count, dtype: int64

In [25]:
df["phcn_electricity"].value_counts(dropna=False)
df["chalkboard_each_classroom_yn"].value_counts(dropna=False)

chalkboard_each_classroom_yn
False    50390
True     46116
NaN       2161
Name: count, dtype: int64

In [18]:
df.describe()

,num_tchrs_with_nce,num_tchr_full_time,num_students_total,num_classrms_total,num_toilets_total,num_students_male,num_students_female,num_tchrs_male,num_tchrs_female,latitude,longitude
count,95137.000000,96503.000000,93405.000000,95375.000000,95705.000000,94292.000000,94321.000000,94987.000000,95348.000000,98667.000000,98667.000000
mean,7.017922,11.666197,335.406306,8.443512,2.546722,187.804628,169.837438,5.723583,5.957985,8.636626,7.183757
std,8.045479,14.033793,343.354223,7.110507,5.768857,257.891030,227.880995,6.205914,8.519480,2.403356,2.353375
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.280918,2.707594
25%,2.000000,4.000000,118.000000,4.000000,0.000000,59.000000,50.000000,2.000000,0.000000,6.671873,5.327685
50%,5.000000,8.000000,223.000000,6.000000,0.000000,114.000000,100.000000,4.000000,3.000000,8.140478,7.303945
75%,9.000000,14.000000,419.000000,11.000000,4.000000,220.000000,200.000000,7.000000,8.000000,10.631606,8.566094
max,100.000000,899.000000,2355.000000,514.000000,418.000000,7677.000000,6689.000000,100.000000,100.000000,13.875585,14.636391

In [26]:
# Convert the 3 columns to boolean

boolean_columns = [
    "improved_water_supply",
    "improved_sanitation",
    "phcn_electricity",
    "chalkboard_each_classroom_yn"
]

for column in boolean_columns:
    df[column] = df[column].astype("boolean")

In [27]:
df.dtypes

facility_name                       str
facility_type_display               str
improved_water_supply           boolean
improved_sanitation             boolean
chalkboard_each_classroom_yn    boolean
num_tchrs_with_nce              float64
num_tchr_full_time              float64
num_students_total              float64
num_classrms_total              float64
phcn_electricity                boolean
num_toilets_total               float64
num_students_male               float64
num_students_female             float64
num_tchrs_male                  float64
num_tchrs_female                float64
date_of_survey                      str
education_type                      str
facility_id                         str
community                           str
ward                                str
management                          str
sector                              str
formhub_photo_id                    str
gps                                 str
survey_id                           str
unique_lga                          str
latitude                        float64
longitude                       float64
dtype: object

In [28]:
# Deal with missing values

missing = pd.DataFrame({
    "Missing": df.isna().sum(),
    "Percentage": (df.isna().sum()/ len(df)) * 100
})

missing = missing[missing["Missing"] > 0].sort_values(
    "Percentage",
    ascending=False
)

missing

                              Missing  Percentage
num_students_total               5262    5.333090
num_students_male                4375    4.434107
num_students_female              4346    4.404715
num_tchrs_male                   3680    3.729717
num_tchrs_with_nce               3530    3.577691
num_tchrs_female                 3319    3.363840
num_classrms_total               3292    3.336475
num_toilets_total                2962    3.002017
num_tchr_full_time               2164    2.193236
chalkboard_each_classroom_yn     2161    2.190195
management                       1223    1.239523
facility_type_display             903    0.915200
ward                              771    0.781416
improved_sanitation               297    0.301012
improved_water_supply             279    0.282769
phcn_electricity                  277    0.280742
community                         238    0.241215
education_type                    221    0.223986
facility_name                     215    0.217905
unique_lga                          1    0.001014

In [29]:
# Identify Numerical Columns
for i, column in enumerate(df.columns):
    print(i, column)

0 facility_name
1 facility_type_display
2 improved_water_supply
3 improved_sanitation
4 chalkboard_each_classroom_yn
5 num_tchrs_with_nce
6 num_tchr_full_time
7 num_students_total
8 num_classrms_total
9 phcn_electricity
10 num_toilets_total
11 num_students_male
12 num_students_female
13 num_tchrs_male
14 num_tchrs_female
15 date_of_survey
16 education_type
17 facility_id
18 community
19 ward
20 management
21 sector
22 formhub_photo_id
23 gps
24 survey_id
25 unique_lga
26 latitude
27 longitude

In [31]:
df["num_students_total"].describe()

count    93405.000000
mean       335.406306
std        343.354223
min          0.000000
25%        118.000000
50%        223.000000
75%        419.000000
max       2355.000000
Name: num_students_total, dtype: float64

In [34]:
df.rename(columns={
    "facility_name": "Facility Name",
    "facility_type_display": "Facility Type Display",
    "improved_water_supply": "Improved Water Supply",
    "improved_sanitation": "Improved Sanitation",
    "chalkboard_each_classroom_yn": "Chalkboard in Each Classes (T/F)",
    "num_tchrs_with_nce": "Num of Teachers With NCE",
    "num_tchr_full_time": "Num Of Fulltime Teachers",
    "num_students_total": "Total Number Of Students",
    "num_classrms_total": "Total Number Of Classrooms",
    "phcn_electricity": "PHCN Electricity",
    "num_toilets_total": "Total Number Of Toilets",
    "num_students_male":"Number Of Male Students",
    "num_students_female": "Number Of Female Students",
    "num_tchrs_male": "Number Of Male Teachers",
    "num_tchrs_female": "Number Of Female Teachers",
    "date_of_survey": "Date Of Survey",
    "education_type": "Education Type",
    "facility_id": "Facility ID",
    "community": "Community",
    "ward": "Ward",
    "management": "Management",
    "sector": "Sector",
    "formhub_photo_id": "Form Hub Photo ID",
    "gps": "GPS",
    "survey_id":"Survey ID",
    "unique_lga": "Unique LGA",
    "latitude": "Latitude",
    "longitude": "Longitude"
    
    
    
}, inplace=True)
df.head()

,Facility Name,Facility Type Display,Improved Water Supply,Improved Sanitation,Chalkboard in Each Classes (T/F),Num of Teachers With NCE,Num Of Fulltime Teachers,Total Number Of Students,Total Number Of Classrooms,PHCN Electricity,...,Community,Ward,Management,Sector,Form Hub Photo ID,GPS,Survey ID,Unique LGA,Latitude,Longitude
0,CPS SWALI,Primary school only,True,True,False,9.0,9.0,776.0,12.0,False,...,Swali,3,public,education,1393404015008.jpg,4.91691036 6.27412844 31.5 5.0,51885096-65a1-4f1f-8c2a-3b11d9ae40bb,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,False,False,<NA>,NaN,NaN,NaN,NaN,False,...,Mpape,Dutse,private,education,1396960914896.jpg,9.140918333333333 7.496761666666667 697.0 4.5,7f3ea41a-e4cb-41dd-85fc-5fa54c42d09f,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,True,True,False,9.0,11.0,283.0,9.0,False,...,Pabeyi,Dobi,public,education,1397575395444.jpg,9.174855 7.0220616666666675 236.8 5.0,56f2e625-ec43-4c39-97a8-d6379dceefa2,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,False,True,False,4.0,5.0,247.0,7.0,False,...,Pagadna,Dobi,public,education,1398262573409.jpg,9.115846666666666 6.962314999999999 216.5 4.4,2932eda8-64b1-4068-8412-3b2e099062fc,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,False,True,True,4.0,8.0,66.0,10.0,True,...,Mpape,Dutse,private,education,1396959110576.jpg,9.141155 7.499665000000001 693.2 4.7,e17acb1e-364a-4a90-9384-0d612bb240c5,fct_bwari,9.141155,7.499665

In [37]:
# df.drop(columns=["Form Hub Photo ID", "GPS", "Survey ID", "Facility ID" ], inplace=True)
df.head()

,Facility Name,Facility Type Display,Improved Water Supply,Improved Sanitation,Chalkboard in Each Classes (T/F),Num of Teachers With NCE,Num Of Fulltime Teachers,Total Number Of Students,Total Number Of Classrooms,PHCN Electricity,...,Number Of Female Teachers,Date Of Survey,Education Type,Community,Ward,Management,Sector,Unique LGA,Latitude,Longitude
0,CPS SWALI,Primary school only,True,True,False,9.0,9.0,776.0,12.0,False,...,4.0,2014-03-04,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,False,False,<NA>,NaN,NaN,NaN,NaN,False,...,NaN,2014-05-02,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,True,True,False,9.0,11.0,283.0,9.0,False,...,2.0,2014-05-02,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,False,True,False,4.0,5.0,247.0,7.0,False,...,0.0,2014-04-25,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,False,True,True,4.0,8.0,66.0,10.0,True,...,6.0,2014-04-25,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665